// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mem_streaming_mem_streaming,hls_ip_2023_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=87,HLS_SYN_TPT=none,HLS_SYN_MEM=60,HLS_SYN_DSP=0,HLS_SYN_FF=3268,HLS_SYN_LUT=3864,HLS_VERSION=2023_2_1}" *)

module mem_streaming (
        ap_clk,
        ap_rst_n,
        m_axi_out_r_AWVALID,
        m_axi_out_r_AWREADY,
        m_axi_out_r_AWADDR,
        m_axi_out_r_AWID,
        m_axi_out_r_AWLEN,
        m_axi_out_r_AWSIZE,
        m_axi_out_r_AWBURST,
        m_axi_out_r_AWLOCK,
        m_axi_out_r_AWCACHE,
        m_axi_out_r_AWPROT,
        m_axi_out_r_AWQOS,
        m_axi_out_r_AWREGION,
        m_axi_out_r_AWUSER,
        m_axi_out_r_WVALID,
        m_axi_out_r_WREADY,
        m_axi_out_r_WDATA,
        m_axi_out_r_WSTRB,
        m_axi_out_r_WLAST,
        m_axi_out_r_WID,
        m_axi_out_r_WUSER,
        m_axi_out_r_ARVALID,
        m_axi_out_r_ARREADY,
        m_axi_out_r_ARADDR,
        m_axi_out_r_ARID,
        m_axi_out_r_ARLEN,
        m_axi_out_r_ARSIZE,
        m_axi_out_r_ARBURST,
        m_axi_out_r_ARLOCK,
        m_axi_out_r_ARCACHE,
        m_axi_out_r_ARPROT,
        m_axi_out_r_ARQOS,
        m_axi_out_r_ARREGION,
        m_axi_out_r_ARUSER,
        m_axi_out_r_RVALID,
        m_axi_out_r_RREADY,
        m_axi_out_r_RDATA,
        m_axi_out_r_RLAST,
        m_axi_out_r_RID,
        m_axi_out_r_RUSER,
        m_axi_out_r_RRESP,
        m_axi_out_r_BVALID,
        m_axi_out_r_BREADY,
        m_axi_out_r_BRESP,
        m_axi_out_r_BID,
        m_axi_out_r_BUSER,
        m_axi_in_r_AWVALID,
        m_axi_in_r_AWREADY,
        m_axi_in_r_AWADDR,
        m_axi_in_r_AWID,
        m_axi_in_r_AWLEN,
        m_axi_in_r_AWSIZE,
        m_axi_in_r_AWBURST,
        m_axi_in_r_AWLOCK,
        m_axi_in_r_AWCACHE,
        m_axi_in_r_AWPROT,
        m_axi_in_r_AWQOS,
        m_axi_in_r_AWREGION,
        m_axi_in_r_AWUSER,
        m_axi_in_r_WVALID,
        m_axi_in_r_WREADY,
        m_axi_in_r_WDATA,
        m_axi_in_r_WSTRB,
        m_axi_in_r_WLAST,
        m_axi_in_r_WID,
        m_axi_in_r_WUSER,
        m_axi_in_r_ARVALID,
        m_axi_in_r_ARREADY,
        m_axi_in_r_ARADDR,
        m_axi_in_r_ARID,
        m_axi_in_r_ARLEN,
        m_axi_in_r_ARSIZE,
        m_axi_in_r_ARBURST,
        m_axi_in_r_ARLOCK,
        m_axi_in_r_ARCACHE,
        m_axi_in_r_ARPROT,
        m_axi_in_r_ARQOS,
        m_axi_in_r_ARREGION,
        m_axi_in_r_ARUSER,
        m_axi_in_r_RVALID,
        m_axi_in_r_RREADY,
        m_axi_in_r_RDATA,
        m_axi_in_r_RLAST,
        m_axi_in_r_RID,
        m_axi_in_r_RUSER,
        m_axi_in_r_RRESP,
        m_axi_in_r_BVALID,
        m_axi_in_r_BREADY,
        m_axi_in_r_BRESP,
        m_axi_in_r_BID,
        m_axi_in_r_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_IN_R_ID_WIDTH = 1;
parameter    C_M_AXI_IN_R_ADDR_WIDTH = 64;
parameter    C_M_AXI_IN_R_DATA_WIDTH = 256;
parameter    C_M_AXI_IN_R_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IN_R_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IN_R_WUSER_WIDTH = 1;
parameter    C_M_AXI_IN_R_RUSER_WIDTH = 1;
parameter    C_M_AXI_IN_R_BUSER_WIDTH = 1;
parameter    C_M_AXI_IN_R_USER_VALUE = 0;
parameter    C_M_AXI_IN_R_PROT_VALUE = 0;
parameter    C_M_AXI_IN_R_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_OUT_R_ID_WIDTH = 1;
parameter    C_M_AXI_OUT_R_ADDR_WIDTH = 64;
parameter    C_M_AXI_OUT_R_DATA_WIDTH = 256;
parameter    C_M_AXI_OUT_R_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_USER_VALUE = 0;
parameter    C_M_AXI_OUT_R_PROT_VALUE = 0;
parameter    C_M_AXI_OUT_R_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_IN_R_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_OUT_R_WSTRB_WIDTH = (256 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_out_r_AWVALID;
input   m_axi_out_r_AWREADY;
output  [C_M_AXI_OUT_R_ADDR_WIDTH - 1:0] m_axi_out_r_AWADDR;
output  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_AWID;
output  [7:0] m_axi_out_r_AWLEN;
output  [2:0] m_axi_out_r_AWSIZE;
output  [1:0] m_axi_out_r_AWBURST;
output  [1:0] m_axi_out_r_AWLOCK;
output  [3:0] m_axi_out_r_AWCACHE;
output  [2:0] m_axi_out_r_AWPROT;
output  [3:0] m_axi_out_r_AWQOS;
output  [3:0] m_axi_out_r_AWREGION;
output  [C_M_AXI_OUT_R_AWUSER_WIDTH - 1:0] m_axi_out_r_AWUSER;
output   m_axi_out_r_WVALID;
input   m_axi_out_r_WREADY;
output  [C_M_AXI_OUT_R_DATA_WIDTH - 1:0] m_axi_out_r_WDATA;
output  [C_M_AXI_OUT_R_WSTRB_WIDTH - 1:0] m_axi_out_r_WSTRB;
output   m_axi_out_r_WLAST;
output  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_WID;
output  [C_M_AXI_OUT_R_WUSER_WIDTH - 1:0] m_axi_out_r_WUSER;
output   m_axi_out_r_ARVALID;
input   m_axi_out_r_ARREADY;
output  [C_M_AXI_OUT_R_ADDR_WIDTH - 1:0] m_axi_out_r_ARADDR;
output  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_ARID;
output  [7:0] m_axi_out_r_ARLEN;
output  [2:0] m_axi_out_r_ARSIZE;
output  [1:0] m_axi_out_r_ARBURST;
output  [1:0] m_axi_out_r_ARLOCK;
output  [3:0] m_axi_out_r_ARCACHE;
output  [2:0] m_axi_out_r_ARPROT;
output  [3:0] m_axi_out_r_ARQOS;
output  [3:0] m_axi_out_r_ARREGION;
output  [C_M_AXI_OUT_R_ARUSER_WIDTH - 1:0] m_axi_out_r_ARUSER;
input   m_axi_out_r_RVALID;
output   m_axi_out_r_RREADY;
input  [C_M_AXI_OUT_R_DATA_WIDTH - 1:0] m_axi_out_r_RDATA;
input   m_axi_out_r_RLAST;
input  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_RID;
input  [C_M_AXI_OUT_R_RUSER_WIDTH - 1:0] m_axi_out_r_RUSER;
input  [1:0] m_axi_out_r_RRESP;
input   m_axi_out_r_BVALID;
output   m_axi_out_r_BREADY;
input  [1:0] m_axi_out_r_BRESP;
input  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_BID;
input  [C_M_AXI_OUT_R_BUSER_WIDTH - 1:0] m_axi_out_r_BUSER;
output   m_axi_in_r_AWVALID;
input   m_axi_in_r_AWREADY;
output  [C_M_AXI_IN_R_ADDR_WIDTH - 1:0] m_axi_in_r_AWADDR;
output  [C_M_AXI_IN_R_ID_WIDTH - 1:0] m_axi_in_r_AWID;
output  [7:0] m_axi_in_r_AWLEN;
output  [2:0] m_axi_in_r_AWSIZE;
output  [1:0] m_axi_in_r_AWBURST;
output  [1:0] m_axi_in_r_AWLOCK;
output  [3:0] m_axi_in_r_AWCACHE;
output  [2:0] m_axi_in_r_AWPROT;
output  [3:0] m_axi_in_r_AWQOS;
output  [3:0] m_axi_in_r_AWREGION;
output  [C_M_AXI_IN_R_AWUSER_WIDTH - 1:0] m_axi_in_r_AWUSER;
output   m_axi_in_r_WVALID;
input   m_axi_in_r_WREADY;
output  [C_M_AXI_IN_R_DATA_WIDTH - 1:0] m_axi_in_r_WDATA;
output  [C_M_AXI_IN_R_WSTRB_WIDTH - 1:0] m_axi_in_r_WSTRB;
output   m_axi_in_r_WLAST;
output  [C_M_AXI_IN_R_ID_WIDTH - 1:0] m_axi_in_r_WID;
output  [C_M_AXI_IN_R_WUSER_WIDTH - 1:0] m_axi_in_r_WUSER;
output   m_axi_in_r_ARVALID;
input   m_axi_in_r_ARREADY;
output  [C_M_AXI_IN_R_ADDR_WIDTH - 1:0] m_axi_in_r_ARADDR;
output  [C_M_AXI_IN_R_ID_WIDTH - 1:0] m_axi_in_r_ARID;
output  [7:0] m_axi_in_r_ARLEN;
output  [2:0] m_axi_in_r_ARSIZE;
output  [1:0] m_axi_in_r_ARBURST;
output  [1:0] m_axi_in_r_ARLOCK;
output  [3:0] m_axi_in_r_ARCACHE;
output  [2:0] m_axi_in_r_ARPROT;
output  [3:0] m_axi_in_r_ARQOS;
output  [3:0] m_axi_in_r_ARREGION;
output  [C_M_AXI_IN_R_ARUSER_WIDTH - 1:0] m_axi_in_r_ARUSER;
input   m_axi_in_r_RVALID;
output   m_axi_in_r_RREADY;
input  [C_M_AXI_IN_R_DATA_WIDTH - 1:0] m_axi_in_r_RDATA;
input   m_axi_in_r_RLAST;
input  [C_M_AXI_IN_R_ID_WIDTH - 1:0] m_axi_in_r_RID;
input  [C_M_AXI_IN_R_RUSER_WIDTH - 1:0] m_axi_in_r_RUSER;
input  [1:0] m_axi_in_r_RRESP;
input   m_axi_in_r_BVALID;
output   m_axi_in_r_BREADY;
input  [1:0] m_axi_in_r_BRESP;
input  [C_M_AXI_IN_R_ID_WIDTH - 1:0] m_axi_in_r_BID;
input  [C_M_AXI_IN_R_BUSER_WIDTH - 1:0] m_axi_in_r_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] data_out;
wire   [63:0] data_in;
reg    out_r_blk_n_AW;
wire    ap_CS_fsm_state13;
reg    out_r_blk_n_B;
wire    ap_CS_fsm_state20;
reg    in_r_blk_n_AR;
wire    ap_CS_fsm_state2;
reg   [58:0] trunc_ln9_reg_186;
reg   [58:0] trunc_ln_reg_192;
reg   [3:0] data_buf_address0;
reg    data_buf_ce0;
reg    data_buf_we0;
reg   [15:0] data_buf_d0;
wire   [15:0] data_buf_q0;
reg   [3:0] data_buf_address1;
reg    data_buf_ce1;
reg    data_buf_we1;
wire   [15:0] data_buf_q1;
reg   [3:0] data_buf_1_address0;
reg    data_buf_1_ce0;
reg    data_buf_1_we0;
reg   [15:0] data_buf_1_d0;
wire   [15:0] data_buf_1_q0;
reg   [3:0] data_buf_1_address1;
reg    data_buf_1_ce1;
reg    data_buf_1_we1;
wire   [15:0] data_buf_1_q1;
reg   [3:0] data_buf_2_address0;
reg    data_buf_2_ce0;
reg    data_buf_2_we0;
reg   [15:0] data_buf_2_d0;
wire   [15:0] data_buf_2_q0;
reg   [3:0] data_buf_2_address1;
reg    data_buf_2_ce1;
reg    data_buf_2_we1;
wire   [15:0] data_buf_2_q1;
reg   [3:0] data_buf_3_address0;
reg    data_buf_3_ce0;
reg    data_buf_3_we0;
reg   [15:0] data_buf_3_d0;
wire   [15:0] data_buf_3_q0;
reg   [3:0] data_buf_3_address1;
reg    data_buf_3_ce1;
reg    data_buf_3_we1;
wire   [15:0] data_buf_3_q1;
reg   [3:0] data_buf_4_address0;
reg    data_buf_4_ce0;
reg    data_buf_4_we0;
reg   [15:0] data_buf_4_d0;
wire   [15:0] data_buf_4_q0;
reg   [3:0] data_buf_4_address1;
reg    data_buf_4_ce1;
reg    data_buf_4_we1;
wire   [15:0] data_buf_4_q1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_done;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_idle;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_ready;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWVALID;
wire   [63:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWADDR;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWID;
wire   [31:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWLEN;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWSIZE;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWBURST;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWLOCK;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWCACHE;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWPROT;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWQOS;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWREGION;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWUSER;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WVALID;
wire   [255:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WDATA;
wire   [31:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WSTRB;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WLAST;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WID;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WUSER;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARVALID;
wire   [63:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARADDR;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARID;
wire   [31:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARLEN;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARSIZE;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARBURST;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARLOCK;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARCACHE;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARPROT;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARQOS;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARREGION;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARUSER;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_RREADY;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_BREADY;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_ce1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_we1;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_d1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_ce1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_we1;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_d1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_ce1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_we1;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_d1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_ce1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_we1;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_d1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_ce1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_we1;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_d1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_done;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_idle;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_ready;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_ce0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_we0;
wire   [15:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_d0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_ce1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_done;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_idle;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_ready;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWVALID;
wire   [63:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWADDR;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWID;
wire   [31:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWLEN;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWSIZE;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWBURST;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWLOCK;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWCACHE;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWPROT;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWQOS;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWREGION;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWUSER;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WVALID;
wire   [255:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WDATA;
wire   [31:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WSTRB;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WLAST;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WID;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WUSER;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARVALID;
wire   [63:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARADDR;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARID;
wire   [31:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARLEN;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARSIZE;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARBURST;
wire   [1:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARLOCK;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARCACHE;
wire   [2:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARPROT;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARQOS;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARREGION;
wire   [0:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARUSER;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_RREADY;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_BREADY;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_ce0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_ce0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_ce0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_ce0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_ce1;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_address0;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_ce0;
wire   [3:0] grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_address1;
wire    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_ce1;
wire    in_r_AWREADY;
wire    in_r_WREADY;
reg    in_r_ARVALID;
wire    in_r_ARREADY;
reg   [63:0] in_r_ARADDR;
reg   [31:0] in_r_ARLEN;
wire    in_r_RVALID;
reg    in_r_RREADY;
wire   [255:0] in_r_RDATA;
wire   [8:0] in_r_RFIFONUM;
wire    in_r_BVALID;
reg    out_r_AWVALID;
wire    out_r_AWREADY;
reg   [63:0] out_r_AWADDR;
reg   [31:0] out_r_AWLEN;
reg    out_r_WVALID;
wire    out_r_WREADY;
wire    out_r_ARREADY;
wire    out_r_RVALID;
wire   [255:0] out_r_RDATA;
wire   [8:0] out_r_RFIFONUM;
wire    out_r_BVALID;
reg    out_r_BREADY;
reg    grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire  signed [63:0] sext_ln9_fu_166_p1;
wire  signed [63:0] sext_ln25_fu_176_p1;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start_reg = 1'b0;
#0 grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start_reg = 1'b0;
#0 grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start_reg = 1'b0;
end

mem_streaming_data_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
data_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_buf_address0),
    .ce0(data_buf_ce0),
    .we0(data_buf_we0),
    .d0(data_buf_d0),
    .q0(data_buf_q0),
    .address1(data_buf_address1),
    .ce1(data_buf_ce1),
    .we1(data_buf_we1),
    .d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_d1),
    .q1(data_buf_q1)
);

mem_streaming_data_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
data_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_buf_1_address0),
    .ce0(data_buf_1_ce0),
    .we0(data_buf_1_we0),
    .d0(data_buf_1_d0),
    .q0(data_buf_1_q0),
    .address1(data_buf_1_address1),
    .ce1(data_buf_1_ce1),
    .we1(data_buf_1_we1),
    .d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_d1),
    .q1(data_buf_1_q1)
);

mem_streaming_data_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
data_buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_buf_2_address0),
    .ce0(data_buf_2_ce0),
    .we0(data_buf_2_we0),
    .d0(data_buf_2_d0),
    .q0(data_buf_2_q0),
    .address1(data_buf_2_address1),
    .ce1(data_buf_2_ce1),
    .we1(data_buf_2_we1),
    .d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_d1),
    .q1(data_buf_2_q1)
);

mem_streaming_data_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
data_buf_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_buf_3_address0),
    .ce0(data_buf_3_ce0),
    .we0(data_buf_3_we0),
    .d0(data_buf_3_d0),
    .q0(data_buf_3_q0),
    .address1(data_buf_3_address1),
    .ce1(data_buf_3_ce1),
    .we1(data_buf_3_we1),
    .d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_d1),
    .q1(data_buf_3_q1)
);

mem_streaming_data_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
data_buf_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_buf_4_address0),
    .ce0(data_buf_4_ce0),
    .we0(data_buf_4_we0),
    .d0(data_buf_4_d0),
    .q0(data_buf_4_q0),
    .address1(data_buf_4_address1),
    .ce1(data_buf_4_ce1),
    .we1(data_buf_4_we1),
    .d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_d1),
    .q1(data_buf_4_q1)
);

mem_streaming_mem_streaming_Pipeline_VITIS_LOOP_9_1 grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start),
    .ap_done(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_done),
    .ap_idle(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_idle),
    .ap_ready(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_ready),
    .m_axi_in_r_AWVALID(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWVALID),
    .m_axi_in_r_AWREADY(1'b0),
    .m_axi_in_r_AWADDR(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWADDR),
    .m_axi_in_r_AWID(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWID),
    .m_axi_in_r_AWLEN(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWLEN),
    .m_axi_in_r_AWSIZE(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWSIZE),
    .m_axi_in_r_AWBURST(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWBURST),
    .m_axi_in_r_AWLOCK(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWLOCK),
    .m_axi_in_r_AWCACHE(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWCACHE),
    .m_axi_in_r_AWPROT(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWPROT),
    .m_axi_in_r_AWQOS(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWQOS),
    .m_axi_in_r_AWREGION(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWREGION),
    .m_axi_in_r_AWUSER(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_AWUSER),
    .m_axi_in_r_WVALID(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WVALID),
    .m_axi_in_r_WREADY(1'b0),
    .m_axi_in_r_WDATA(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WDATA),
    .m_axi_in_r_WSTRB(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WSTRB),
    .m_axi_in_r_WLAST(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WLAST),
    .m_axi_in_r_WID(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WID),
    .m_axi_in_r_WUSER(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_WUSER),
    .m_axi_in_r_ARVALID(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARVALID),
    .m_axi_in_r_ARREADY(in_r_ARREADY),
    .m_axi_in_r_ARADDR(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARADDR),
    .m_axi_in_r_ARID(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARID),
    .m_axi_in_r_ARLEN(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARLEN),
    .m_axi_in_r_ARSIZE(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARSIZE),
    .m_axi_in_r_ARBURST(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARBURST),
    .m_axi_in_r_ARLOCK(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARLOCK),
    .m_axi_in_r_ARCACHE(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARCACHE),
    .m_axi_in_r_ARPROT(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARPROT),
    .m_axi_in_r_ARQOS(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARQOS),
    .m_axi_in_r_ARREGION(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARREGION),
    .m_axi_in_r_ARUSER(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARUSER),
    .m_axi_in_r_RVALID(in_r_RVALID),
    .m_axi_in_r_RREADY(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_RREADY),
    .m_axi_in_r_RDATA(in_r_RDATA),
    .m_axi_in_r_RLAST(1'b0),
    .m_axi_in_r_RID(1'd0),
    .m_axi_in_r_RFIFONUM(in_r_RFIFONUM),
    .m_axi_in_r_RUSER(1'd0),
    .m_axi_in_r_RRESP(2'd0),
    .m_axi_in_r_BVALID(1'b0),
    .m_axi_in_r_BREADY(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_BREADY),
    .m_axi_in_r_BRESP(2'd0),
    .m_axi_in_r_BID(1'd0),
    .m_axi_in_r_BUSER(1'd0),
    .sext_ln9(trunc_ln9_reg_186),
    .data_buf_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_address0),
    .data_buf_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_ce0),
    .data_buf_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_we0),
    .data_buf_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_d0),
    .data_buf_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_address1),
    .data_buf_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_ce1),
    .data_buf_we1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_we1),
    .data_buf_d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_d1),
    .data_buf_1_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_address0),
    .data_buf_1_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_ce0),
    .data_buf_1_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_we0),
    .data_buf_1_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_d0),
    .data_buf_1_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_address1),
    .data_buf_1_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_ce1),
    .data_buf_1_we1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_we1),
    .data_buf_1_d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_d1),
    .data_buf_2_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_address0),
    .data_buf_2_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_ce0),
    .data_buf_2_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_we0),
    .data_buf_2_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_d0),
    .data_buf_2_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_address1),
    .data_buf_2_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_ce1),
    .data_buf_2_we1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_we1),
    .data_buf_2_d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_d1),
    .data_buf_3_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_address0),
    .data_buf_3_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_ce0),
    .data_buf_3_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_we0),
    .data_buf_3_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_d0),
    .data_buf_3_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_address1),
    .data_buf_3_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_ce1),
    .data_buf_3_we1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_we1),
    .data_buf_3_d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_d1),
    .data_buf_4_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_address0),
    .data_buf_4_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_ce0),
    .data_buf_4_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_we0),
    .data_buf_4_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_d0),
    .data_buf_4_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_address1),
    .data_buf_4_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_ce1),
    .data_buf_4_we1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_we1),
    .data_buf_4_d1(grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_d1)
);

mem_streaming_mem_streaming_Pipeline_VITIS_LOOP_40_1 grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start),
    .ap_done(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_done),
    .ap_idle(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_idle),
    .ap_ready(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_ready),
    .data_buf_4_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_address0),
    .data_buf_4_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_ce0),
    .data_buf_4_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_we0),
    .data_buf_4_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_d0),
    .data_buf_4_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_address1),
    .data_buf_4_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_ce1),
    .data_buf_4_q1(data_buf_4_q1),
    .data_buf_3_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_address0),
    .data_buf_3_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_ce0),
    .data_buf_3_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_we0),
    .data_buf_3_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_d0),
    .data_buf_3_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_address1),
    .data_buf_3_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_ce1),
    .data_buf_3_q1(data_buf_3_q1),
    .data_buf_2_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_address0),
    .data_buf_2_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_ce0),
    .data_buf_2_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_we0),
    .data_buf_2_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_d0),
    .data_buf_2_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_address1),
    .data_buf_2_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_ce1),
    .data_buf_2_q1(data_buf_2_q1),
    .data_buf_1_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_address0),
    .data_buf_1_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_ce0),
    .data_buf_1_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_we0),
    .data_buf_1_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_d0),
    .data_buf_1_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_address1),
    .data_buf_1_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_ce1),
    .data_buf_1_q1(data_buf_1_q1),
    .data_buf_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_address0),
    .data_buf_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_ce0),
    .data_buf_we0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_we0),
    .data_buf_d0(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_d0),
    .data_buf_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_address1),
    .data_buf_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_ce1),
    .data_buf_q1(data_buf_q1)
);

mem_streaming_mem_streaming_Pipeline_VITIS_LOOP_25_1 grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start),
    .ap_done(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_done),
    .ap_idle(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_idle),
    .ap_ready(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_ready),
    .m_axi_out_r_AWVALID(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWVALID),
    .m_axi_out_r_AWREADY(out_r_AWREADY),
    .m_axi_out_r_AWADDR(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWADDR),
    .m_axi_out_r_AWID(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWID),
    .m_axi_out_r_AWLEN(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWLEN),
    .m_axi_out_r_AWSIZE(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWSIZE),
    .m_axi_out_r_AWBURST(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWBURST),
    .m_axi_out_r_AWLOCK(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWLOCK),
    .m_axi_out_r_AWCACHE(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWCACHE),
    .m_axi_out_r_AWPROT(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWPROT),
    .m_axi_out_r_AWQOS(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWQOS),
    .m_axi_out_r_AWREGION(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWREGION),
    .m_axi_out_r_AWUSER(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWUSER),
    .m_axi_out_r_WVALID(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WVALID),
    .m_axi_out_r_WREADY(out_r_WREADY),
    .m_axi_out_r_WDATA(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WDATA),
    .m_axi_out_r_WSTRB(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WSTRB),
    .m_axi_out_r_WLAST(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WLAST),
    .m_axi_out_r_WID(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WID),
    .m_axi_out_r_WUSER(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WUSER),
    .m_axi_out_r_ARVALID(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARVALID),
    .m_axi_out_r_ARREADY(1'b0),
    .m_axi_out_r_ARADDR(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARADDR),
    .m_axi_out_r_ARID(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARID),
    .m_axi_out_r_ARLEN(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARLEN),
    .m_axi_out_r_ARSIZE(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARSIZE),
    .m_axi_out_r_ARBURST(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARBURST),
    .m_axi_out_r_ARLOCK(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARLOCK),
    .m_axi_out_r_ARCACHE(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARCACHE),
    .m_axi_out_r_ARPROT(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARPROT),
    .m_axi_out_r_ARQOS(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARQOS),
    .m_axi_out_r_ARREGION(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARREGION),
    .m_axi_out_r_ARUSER(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_ARUSER),
    .m_axi_out_r_RVALID(1'b0),
    .m_axi_out_r_RREADY(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_RREADY),
    .m_axi_out_r_RDATA(256'd0),
    .m_axi_out_r_RLAST(1'b0),
    .m_axi_out_r_RID(1'd0),
    .m_axi_out_r_RFIFONUM(9'd0),
    .m_axi_out_r_RUSER(1'd0),
    .m_axi_out_r_RRESP(2'd0),
    .m_axi_out_r_BVALID(out_r_BVALID),
    .m_axi_out_r_BREADY(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_BREADY),
    .m_axi_out_r_BRESP(2'd0),
    .m_axi_out_r_BID(1'd0),
    .m_axi_out_r_BUSER(1'd0),
    .sext_ln25(trunc_ln_reg_192),
    .data_buf_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_address0),
    .data_buf_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_ce0),
    .data_buf_q0(data_buf_q0),
    .data_buf_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_address1),
    .data_buf_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_ce1),
    .data_buf_q1(data_buf_q1),
    .data_buf_1_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_address0),
    .data_buf_1_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_ce0),
    .data_buf_1_q0(data_buf_1_q0),
    .data_buf_1_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_address1),
    .data_buf_1_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_ce1),
    .data_buf_1_q1(data_buf_1_q1),
    .data_buf_2_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_address0),
    .data_buf_2_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_ce0),
    .data_buf_2_q0(data_buf_2_q0),
    .data_buf_2_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_address1),
    .data_buf_2_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_ce1),
    .data_buf_2_q1(data_buf_2_q1),
    .data_buf_3_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_address0),
    .data_buf_3_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_ce0),
    .data_buf_3_q0(data_buf_3_q0),
    .data_buf_3_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_address1),
    .data_buf_3_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_ce1),
    .data_buf_3_q1(data_buf_3_q1),
    .data_buf_4_address0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_address0),
    .data_buf_4_ce0(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_ce0),
    .data_buf_4_q0(data_buf_4_q0),
    .data_buf_4_address1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_address1),
    .data_buf_4_ce1(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_ce1),
    .data_buf_4_q1(data_buf_4_q1)
);

mem_streaming_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .data_out(data_out),
    .data_in(data_in),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

mem_streaming_in_r_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_IN_R_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_IN_R_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_IN_R_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_IN_R_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_IN_R_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_IN_R_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_IN_R_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_IN_R_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_IN_R_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_IN_R_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_IN_R_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 256 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
in_r_m_axi_U(
    .AWVALID(m_axi_in_r_AWVALID),
    .AWREADY(m_axi_in_r_AWREADY),
    .AWADDR(m_axi_in_r_AWADDR),
    .AWID(m_axi_in_r_AWID),
    .AWLEN(m_axi_in_r_AWLEN),
    .AWSIZE(m_axi_in_r_AWSIZE),
    .AWBURST(m_axi_in_r_AWBURST),
    .AWLOCK(m_axi_in_r_AWLOCK),
    .AWCACHE(m_axi_in_r_AWCACHE),
    .AWPROT(m_axi_in_r_AWPROT),
    .AWQOS(m_axi_in_r_AWQOS),
    .AWREGION(m_axi_in_r_AWREGION),
    .AWUSER(m_axi_in_r_AWUSER),
    .WVALID(m_axi_in_r_WVALID),
    .WREADY(m_axi_in_r_WREADY),
    .WDATA(m_axi_in_r_WDATA),
    .WSTRB(m_axi_in_r_WSTRB),
    .WLAST(m_axi_in_r_WLAST),
    .WID(m_axi_in_r_WID),
    .WUSER(m_axi_in_r_WUSER),
    .ARVALID(m_axi_in_r_ARVALID),
    .ARREADY(m_axi_in_r_ARREADY),
    .ARADDR(m_axi_in_r_ARADDR),
    .ARID(m_axi_in_r_ARID),
    .ARLEN(m_axi_in_r_ARLEN),
    .ARSIZE(m_axi_in_r_ARSIZE),
    .ARBURST(m_axi_in_r_ARBURST),
    .ARLOCK(m_axi_in_r_ARLOCK),
    .ARCACHE(m_axi_in_r_ARCACHE),
    .ARPROT(m_axi_in_r_ARPROT),
    .ARQOS(m_axi_in_r_ARQOS),
    .ARREGION(m_axi_in_r_ARREGION),
    .ARUSER(m_axi_in_r_ARUSER),
    .RVALID(m_axi_in_r_RVALID),
    .RREADY(m_axi_in_r_RREADY),
    .RDATA(m_axi_in_r_RDATA),
    .RLAST(m_axi_in_r_RLAST),
    .RID(m_axi_in_r_RID),
    .RUSER(m_axi_in_r_RUSER),
    .RRESP(m_axi_in_r_RRESP),
    .BVALID(m_axi_in_r_BVALID),
    .BREADY(m_axi_in_r_BREADY),
    .BRESP(m_axi_in_r_BRESP),
    .BID(m_axi_in_r_BID),
    .BUSER(m_axi_in_r_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(in_r_ARVALID),
    .I_ARREADY(in_r_ARREADY),
    .I_ARADDR(in_r_ARADDR),
    .I_ARLEN(in_r_ARLEN),
    .I_RVALID(in_r_RVALID),
    .I_RREADY(in_r_RREADY),
    .I_RDATA(in_r_RDATA),
    .I_RFIFONUM(in_r_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(in_r_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(in_r_WREADY),
    .I_WDATA(256'd0),
    .I_WSTRB(32'd0),
    .I_BVALID(in_r_BVALID),
    .I_BREADY(1'b0)
);

mem_streaming_out_r_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUT_R_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUT_R_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUT_R_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUT_R_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUT_R_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUT_R_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUT_R_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUT_R_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_OUT_R_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUT_R_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUT_R_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 256 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
out_r_m_axi_U(
    .AWVALID(m_axi_out_r_AWVALID),
    .AWREADY(m_axi_out_r_AWREADY),
    .AWADDR(m_axi_out_r_AWADDR),
    .AWID(m_axi_out_r_AWID),
    .AWLEN(m_axi_out_r_AWLEN),
    .AWSIZE(m_axi_out_r_AWSIZE),
    .AWBURST(m_axi_out_r_AWBURST),
    .AWLOCK(m_axi_out_r_AWLOCK),
    .AWCACHE(m_axi_out_r_AWCACHE),
    .AWPROT(m_axi_out_r_AWPROT),
    .AWQOS(m_axi_out_r_AWQOS),
    .AWREGION(m_axi_out_r_AWREGION),
    .AWUSER(m_axi_out_r_AWUSER),
    .WVALID(m_axi_out_r_WVALID),
    .WREADY(m_axi_out_r_WREADY),
    .WDATA(m_axi_out_r_WDATA),
    .WSTRB(m_axi_out_r_WSTRB),
    .WLAST(m_axi_out_r_WLAST),
    .WID(m_axi_out_r_WID),
    .WUSER(m_axi_out_r_WUSER),
    .ARVALID(m_axi_out_r_ARVALID),
    .ARREADY(m_axi_out_r_ARREADY),
    .ARADDR(m_axi_out_r_ARADDR),
    .ARID(m_axi_out_r_ARID),
    .ARLEN(m_axi_out_r_ARLEN),
    .ARSIZE(m_axi_out_r_ARSIZE),
    .ARBURST(m_axi_out_r_ARBURST),
    .ARLOCK(m_axi_out_r_ARLOCK),
    .ARCACHE(m_axi_out_r_ARCACHE),
    .ARPROT(m_axi_out_r_ARPROT),
    .ARQOS(m_axi_out_r_ARQOS),
    .ARREGION(m_axi_out_r_ARREGION),
    .ARUSER(m_axi_out_r_ARUSER),
    .RVALID(m_axi_out_r_RVALID),
    .RREADY(m_axi_out_r_RREADY),
    .RDATA(m_axi_out_r_RDATA),
    .RLAST(m_axi_out_r_RLAST),
    .RID(m_axi_out_r_RID),
    .RUSER(m_axi_out_r_RUSER),
    .RRESP(m_axi_out_r_RRESP),
    .BVALID(m_axi_out_r_BVALID),
    .BREADY(m_axi_out_r_BREADY),
    .BRESP(m_axi_out_r_BRESP),
    .BID(m_axi_out_r_BID),
    .BUSER(m_axi_out_r_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(out_r_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(out_r_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(out_r_RDATA),
    .I_RFIFONUM(out_r_RFIFONUM),
    .I_AWVALID(out_r_AWVALID),
    .I_AWREADY(out_r_AWREADY),
    .I_AWADDR(out_r_AWADDR),
    .I_AWLEN(out_r_AWLEN),
    .I_WVALID(out_r_WVALID),
    .I_WREADY(out_r_WREADY),
    .I_WDATA(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WDATA),
    .I_WSTRB(grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WSTRB),
    .I_BVALID(out_r_BVALID),
    .I_BREADY(out_r_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start_reg <= 1'b1;
        end else if ((grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_ready == 1'b1)) begin
            grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start_reg <= 1'b1;
        end else if ((grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_ready == 1'b1)) begin
            grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start_reg <= 1'b1;
        end else if ((grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_ready == 1'b1)) begin
            grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln9_reg_186 <= {{data_in[63:5]}};
        trunc_ln_reg_192 <= {{data_out[63:5]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if (((out_r_AWREADY == 1'b0) | (grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_done == 1'b0))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_r_BVALID == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((in_r_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((out_r_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_1_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_1_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_1_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_address0;
    end else begin
        data_buf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_1_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_1_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_1_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_address1;
    end else begin
        data_buf_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_1_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_1_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_1_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_ce0;
    end else begin
        data_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_1_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_1_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_1_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_ce1;
    end else begin
        data_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_1_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_1_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_d0;
    end else begin
        data_buf_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_1_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_1_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_we0;
    end else begin
        data_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_1_we1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_1_we1;
    end else begin
        data_buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_2_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_2_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_2_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_address0;
    end else begin
        data_buf_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_2_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_2_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_2_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_address1;
    end else begin
        data_buf_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_2_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_2_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_2_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_ce0;
    end else begin
        data_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_2_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_2_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_2_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_ce1;
    end else begin
        data_buf_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_2_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_2_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_d0;
    end else begin
        data_buf_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_2_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_2_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_we0;
    end else begin
        data_buf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_2_we1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_2_we1;
    end else begin
        data_buf_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_3_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_3_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_3_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_address0;
    end else begin
        data_buf_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_3_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_3_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_3_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_address1;
    end else begin
        data_buf_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_3_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_3_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_3_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_ce0;
    end else begin
        data_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_3_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_3_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_3_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_ce1;
    end else begin
        data_buf_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_3_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_3_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_d0;
    end else begin
        data_buf_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_3_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_3_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_we0;
    end else begin
        data_buf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_3_we1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_3_we1;
    end else begin
        data_buf_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_4_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_4_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_4_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_address0;
    end else begin
        data_buf_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_4_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_address1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_4_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_4_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_address1;
    end else begin
        data_buf_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_4_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_4_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_4_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_ce0;
    end else begin
        data_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_4_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_4_ce1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_4_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_4_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_ce1;
    end else begin
        data_buf_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_4_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_4_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_d0;
    end else begin
        data_buf_4_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_4_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_4_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_4_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_we0;
    end else begin
        data_buf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_4_we1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_4_we1;
    end else begin
        data_buf_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_address0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_address0;
    end else begin
        data_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_address1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_address1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_address1;
    end else begin
        data_buf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_ce0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_ce0;
    end else begin
        data_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        data_buf_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_data_buf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_ce1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_ce1;
    end else begin
        data_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_d0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_d0;
    end else begin
        data_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_buf_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_data_buf_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_we0 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_we0;
    end else begin
        data_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        data_buf_we1 = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_data_buf_we1;
    end else begin
        data_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((in_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_r_ARADDR = sext_ln9_fu_166_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        in_r_ARADDR = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARADDR;
    end else begin
        in_r_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((in_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_r_ARLEN = 32'd5;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        in_r_ARLEN = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARLEN;
    end else begin
        in_r_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((in_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_r_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        in_r_ARVALID = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_ARVALID;
    end else begin
        in_r_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        in_r_RREADY = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_m_axi_in_r_RREADY;
    end else begin
        in_r_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_r_blk_n_AR = m_axi_in_r_ARREADY;
    end else begin
        in_r_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((~((out_r_AWREADY == 1'b0) | (grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        out_r_AWADDR = sext_ln25_fu_176_p1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        out_r_AWADDR = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWADDR;
    end else begin
        out_r_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((out_r_AWREADY == 1'b0) | (grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        out_r_AWLEN = 32'd5;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        out_r_AWLEN = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWLEN;
    end else begin
        out_r_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((out_r_AWREADY == 1'b0) | (grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        out_r_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        out_r_AWVALID = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_AWVALID;
    end else begin
        out_r_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        out_r_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        out_r_BREADY = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_BREADY;
    end else begin
        out_r_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        out_r_WVALID = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_m_axi_out_r_WVALID;
    end else begin
        out_r_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        out_r_blk_n_AW = m_axi_out_r_AWREADY;
    end else begin
        out_r_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        out_r_blk_n_B = m_axi_out_r_BVALID;
    end else begin
        out_r_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((in_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if ((~((out_r_AWREADY == 1'b0) | (grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((out_r_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start = grp_mem_streaming_Pipeline_VITIS_LOOP_25_1_fu_134_ap_start_reg;

assign grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start = grp_mem_streaming_Pipeline_VITIS_LOOP_40_1_fu_125_ap_start_reg;

assign grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start = grp_mem_streaming_Pipeline_VITIS_LOOP_9_1_fu_113_ap_start_reg;

assign sext_ln25_fu_176_p1 = $signed(trunc_ln_reg_192);

assign sext_ln9_fu_166_p1 = $signed(trunc_ln9_reg_186);

endmodule //mem_streaming
